import{a as v,i,S as p}from"./assets/vendor-DFCQGEf1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="https://pixabay.com/api/",q="50210744-4391225cbd715823d75e3ef00",P=15;async function M(t,r=1){const s={key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:P};try{return(await v.get(E,{params:s})).data}catch{i.error({title:"Error",message:"Oops! Failed to load images. Please try again later.",position:"topRight"})}}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),c=new p(".gallery a",{captionsData:"alt",captionDelay:250});function R(t){const r=t.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:l,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a href="${a}">
        <img src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${l}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${S}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",r),c?c.refresh():c=new p(".gallery a",{captionsData:"alt",captionDelay:250})}function B(){m.innerHTML=""}function $(){h.classList.remove("is-hidden")}function O(){h.classList.add("is-hidden")}function A(){y.classList.remove("is-hidden")}function g(){y.classList.add("is-hidden")}const L=document.querySelector(".form"),u=L.querySelector('input[name="search-text"]'),D=document.querySelector(".load-more");let d="",n=1,f=0;L.addEventListener("submit",x);D.addEventListener("click",H);async function x(t){if(t.preventDefault(),i.destroy(),g(),B(),d=u.value.trim(),n=1,!d){i.warning({message:"Please enter a search query.",position:"topRight"});return}await b(),u.value=""}async function H(){n+=1,await b()}async function b(){$();try{const t=await M(d,n);if(f=t.totalHits,t.hits.length===0&&n===1){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}R(t.hits);const r=Math.ceil(f/15);n<r?A():(g(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),n>1&&_()}catch(t){i.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{O()}}function _(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
