import{a as S,i,S as f}from"./assets/vendor-DFCQGEf1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="https://pixabay.com/api/",q="50210744-4391225cbd715823d75e3ef00",v=15;async function P(t,r=1){const s={key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:v};try{return(await S.get(E,{params:s})).data}catch{i.error({title:"Error",message:"Oops! Failed to load images. Please try again later.",position:"topRight"})}}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),c=new f(".gallery a",{captionsData:"alt",captionDelay:250});function M(t){const r=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:l,comments:b,downloads:w})=>`
    <li class="gallery-item">
      <a href="${n}">
        <img src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${l}</p>
        <p><b>Comments:</b> ${b}</p>
        <p><b>Downloads:</b> ${w}</p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",r),c?c.refresh():c=new f(".gallery a",{captionsData:"alt",captionDelay:250})}function R(){p.innerHTML=""}function B(){m.classList.remove("is-hidden")}function $(){m.classList.add("is-hidden")}function O(){h.classList.remove("is-hidden")}function y(){h.classList.add("is-hidden")}const g=document.querySelector(".form"),A=g.querySelector('input[name="search-text"]'),D=document.querySelector(".load-more");let d="",a=1,u=0;g.addEventListener("submit",x);D.addEventListener("click",H);async function x(t){if(t.preventDefault(),i.destroy(),y(),R(),d=A.value.trim(),a=1,!d){i.warning({message:"Please enter a search query.",position:"topRight"});return}await L()}async function H(){a+=1,await L()}async function L(){B();try{const t=await P(d,a);if(u=t.totalHits,t.hits.length===0&&a===1){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}M(t.hits);const r=Math.ceil(u/15);a<r?O():(y(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),a>1&&_()}catch(t){i.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{$()}}function _(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
